// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvycayptlvxzfbbvxtoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2eWNheXB0bHZ4emZiYnZ4dG9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1ODcyNTEsImV4cCI6MjA2OTE2MzI1MX0.k0FIfcNV4xe2IobUgPzjwGp6CzZUFeflhu4p-bgdVNc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});